name: Deploy to GitHub Pages
on:
  # Trigger this workflow on every push to the `main` branch
  # If you use a different branch name, replace `main` with your branch name
  push:
    branches: [ main ]
  # Allow you to manually trigger this workflow from the Actions tab on GitHub
  workflow_dispatch:
# Allow the job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # with:
          # path: . # The root location of your Astro project in the repository. (Optional)
          # node-version: 20 # The specific Node.js version to use for building the site, defaults to 20. (Optional)
          # package-manager: pnpm@latest # Which Node.js package manager should be used to install dependencies and build the site. Automatically detected based on the lockfile in the repository. (Optional)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4